# 将来的には対応する規約の読込
inherit_from: .rubocop_todo.yml

# 追加した規約ファイルの読込
require:
  - rubocop-rails

AllCops:
  # Rubyバージョン指定
  TargetRubyVersion: 2.6.5
  # 除外
  Exclude:
    - 'config.ru'
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

#################### Naming ##############################

# メソッド名のprefixに「set_」「get_」を許可
AccessorMethodName:
  Enabled: false

#################### Style ###############################

# 「and」「or」の使用を許可
AndOr:
  Enabled: false

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# クラスのコメント必須を無視
Documentation:
  Enabled: false
