# 将来的には対応する規約の読込
inherit_from:
  - .rubocop_todo.yml

# 追加した規約ファイルの読込
require:
  - rubocop-rails

AllCops:
  # Rubyバージョン指定
  TargetRubyVersion: 2.6.5
  # 除外
  Exclude:
    - 'vendor/**/*' # rubocop config/default.yml
    - 'config.ru'
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

#################### Layout ###########################

# 1行最大120文字
Layout/LineLength:
  Max: 120

#################### Naming ##############################

# メソッド名のprefixに「set_」「get_」を許可
Naming/AccessorMethodName:
  Enabled: false

#################### Style ###############################

# 「and」「or」の使用を許可
Style/AndOr:
  Enabled: false

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# モジュール名::クラス名の定義を許可
Style/ClassAndModuleChildren:
  Enabled: false

# メソッド呼び出しで :: の使用を許可
Style/ColonMethodCall:
  Enabled: false

# クラスのコメント必須を無視
Style/Documentation:
  Enabled: false

# if 文の中に 3 行程度のブロックを書くのは許容する
Style/GuardClause:
  MinBodyLength: 3

#################### Metrics ###############################

# 一旦 30 までとする
Metrics/AbcSize:
  Max: 30

# rake, RSpec, environments, routes は巨大な block 不可避なので除外
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'Gemfile'
    - 'config/environments/*.rb'
    - 'config/routes.rb'
    - '*.gemspec'

# 20 行を超えるのは migration ファイル以外滅多にない
Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/migrate/*.rb'
