include:
  - "app/**/*.rb"
  - "config/**/*.rb"
  - "lib/**/*.rb"
  - "spec/**/*.rb"
exclude:
  - "vendor/**/*"
  - ".bundle/**/*"
require: []
domains: []
reporters:
  - rubocop
require_paths: []
max_files: 5000
